transaction_log            /var/log/btrbk.log
snapshot_dir               .snapshots
snapshot_preserve_min      2d
snapshot_preserve          14d
target_preserve_min        no
target_preserve            7d 4w 6m

volume /mnt/btr_root
  target /mnt/btr_data/.snapshots
  subvolume root
  subvolume home

volume /mnt/btr_data
  subvolume data
